kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install Flask
  - pip install requests

- name: testing
  image: python
  commands:
  - pip install pytest
  - python -m pytest

- name: fascade
  image: python
  commands:
  - python ./fascade-service/fascade.py

- name: logging
  image: python
  commands:
  - python ./logging-service/log_srv.py

- name: msg
  image: python
  commands:
  - python ./messages-service/msg-srv.py