kind: pipeline
type: docker
name: default

steps:
- name: hello-wrld
  image: python
  commands:
  - echo hello
  - echo world

- name: fascade
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python ./fascade-service/fascade.py

- name: logging
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python ./logging-service/log_srv.py

- name: msg
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python ./messages-service/msg-srv.py
 
