kind: pipeline
type: docker
name: default

steps:
- name: hello-wrld
  image: python
  commands:
  - echo hello
  - echo world

- name: ping
  image: python
  commands:
  - ping -c 3 8.8.8.8

- name: fascade
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python -m py_compile ./fascade-service/fascade.py

- name: logging
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python -m py_compile ./logging-service/log_srv.py

- name: msg
  image: python
  commands:
  - pip install Flask
  - pip install requests
  - python -m py_compile ./messages-service/msg-srv.py
 
