POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg1"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg2"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg3"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg4"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg5"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg6"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg7"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg8"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg9"}

###
POST http://localhost:5001/fascade_service
Content-Type: application/json

{"msg": "msg10"}

###